import logging
import os

def read_binary_logs(file_path):
    try:
        with open(file_path, 'rb') as file:
            data = file.read()
            print(data.decode('utf-8'))  # Adjust encoding as necessary
    except Exception as e:
        print(f"An error occurred while reading the log file: {e}")

def main():
    # Specify the path to your log file generated by main.py
    log_file_path = r"C:\Windows\System32\ChatDev\Phosphorus\PhosphorusAI2024\phosphorus.log"
    read_binary_logs(log_file_path)

if __name__ == "__main__":
    main()

